- src/createUseQuery.ts
Optional params are not marked as optional, this is demonstrated already in the repo under the /pets endpoint.
limit and tags are marked as required in the hook when they should be optional.
> query: fix optional params

- README.md
- examples/react-app/package.json
- package.json
- pnpm-lock.yaml
- src/cli.ts
- src/createExports.ts
- src/createImports.ts
This PR fixes an issue where the peer dependencies were listed for versions of packages that did not exist.
An example being `commander > 10`. Version 10 is the latest of commander.
This also updates all dependencies. 
openapi-typescript-codegen updated and changed `postfix` to `postfixServices` and added a new option for `postfixModals`. Added support for those and documented in the README.
^ this could be seen as a breaking change.
Updated glob to version 10. Glob removed default export.
[See commit](https://github.com/isaacs/node-glob/commit/26673b905684f0058c4594be0b4026b8a22544a7)
> fix(deps): fix breaking peer dep requirements

- examples/react-app/petstore.yaml
- examples/react-app/src/App.tsx
- src/createExports.ts
- src/createUseMutation.ts
- src/createUseQuery.ts
- src/util.ts
React query data is in union with undefined by default.
Previously, we were overriding the default data type of react query.
This causes the issue where the default return type was never marked as undefined.
It should always be possible for the default data to be undefined.
Now we union with undefined.
Exporting the default return type, closes #32
Re-did some of the typings to make it easier to change types.
Added to the example showing how to override the return type for the data, which was addressed in #29
Now, the generator passes the open API descriptions as JSDoc comments to the generated hooks and marks the methods as depreciated if marked in the spec. This closes: #18 
Showing undefined listed in union on return type (as react query would do)
New JSDoc:
With deprecated indicator: …
> patch(return types): union return type with undefined.

- src/createUseMutation.ts
This PR contains a simple capitalization fix. As you can see from the screenshot below, the `{methodName}MutationResult` results in a poorly cased type, in this case `UserClientcreateMutationResult`. This PR should fix this to produce an expected `UserClientCreateMutationResult`
> Fix Capitalization on {methodName}MutationResult

- examples/react-app/request.ts
Followup to: #46 
It seems that the headers dont get passed to the request.
I created a fix for that but it should be considered as "quick and dirty". 
**IMHO** there is a bigger problem with this part of the code generation. Also the names of the props are weird.
> Bug: Fixed missing headers

- src/createImports.mts
We previously imported a data object for each service regardless of whether they had a data object or not.
In this PR, we check all the exports of the services file. From there, we import the services if it ends with `Service` and the data objects if they end with `Data`.
> fix(imports): Correct imports of services with no data object

- package.json
We changed the output file extension of the bin file in version 1.0.0 but missed it here in the package.json. This PR updates the package.json
> Update path to executable

- README.md
The services file was changed when we migrated to @hey-api/openapi-ts
> docs(readme): update import of services

- src/createImports.mts
- src/createSource.mts
> chore: remove unused parameter

- examples/react-app/src/App.tsx
- src/createUseQuery.mts
This PR adds a default parameter initializer if all the properties of the object are optional.
This is an ease-of-use feature that improves DX.
Fixes: Default empty arguments #37
```tsx
// if the props tags and limit are optional (using props)
const { data, error, refetch } = useDefaultServiceFindPets({ tags, limit });
// before this PR, we would have to pass an object to the hook (not using props)
const { data, error, refetch } = useDefaultServiceFindPets({});
// with this PR, we no longer are required to pass an object if all the props are optional (not using props)
const { data, error, refetch }  = useDefaultServiceFindPets();
```
> fix(query): add default parameter initializer

- src/createUseQuery.mts
The reference import path isn't needed as we have already imported all models into the file in question.
This fixes a bug I am having where the entire type with import is being put where a type is located.
The big issue with this import is that it is an absolute path on the computer that generated the code. This is an issue when we want to deploy the code in a library.
This changes:
```typescript
{
prop1: string;
myCustomProp: import("/User/person/project/src/openapi/generated/requests/models").MyCustomProp;
}
```
to 
```typescript
{
prop1: string;
myCustomProp: MyCustomProp;
}
```
I would love to find another way to solve this, as this seems like a hack, but I am still looking for a solution.
A similar change may need to be added to the mutation queries but I do not have an example.
> fix(exports): strip referenced imports of models

- src/createImports.mts
Adds a Warning message instead of throwing an error if no `models` file is found.
Ideally, we would check if `components.schemas` or `components.parameters`  is defined, but the OpenAPI definition is not in scope here.
I didn't see prior examples of throwing errors, and I'm very open suggestions on what should be done there instead.
Fixes #66
> Warn if no models, instead of throwing an error

- src/createUseQuery.mts
This PR allows initialData to be set on the hooks and passed to useQuery.
I am unsure why we initially added it to the omit list.
I believe it was to type it so we could override the types.
It seems the types now propagate the override type to initialData.
I haven't done a lot of testing on this to be specific.
If someone has time to test this build, that would be great.
Fixes #68
> fix: allow initialData

- README.md
- src/cli.mts
- src/generate.mts
In this PR, we correctly accept a value for the enums property and pass it to the the underlying service generator.
Fixes: #72
> fix(enums): take in and pass correct values to service generator

- examples/react-app/package.json
- pnpm-lock.yaml
- src/cli.mts
- src/createExports.mts
Before this patch, only GET queries and POST mutations were created.
We now generate mutation hooks for PUT, PATCH, and DELETE
This patch also fixes an issue where if prettier was installed, it would format the generated service files, changing the quotes around and breaking our checks to determine the HTTP method type.
Example before prettier: `'GET'`
Example after prettier:  `"GET"`
The prettier style of writing functionality was added by the underlying service file generator @hey-api/openapi-ts
I updated the checks to not care about quotes.
Added `prettier` as a dependency of the example app so that prettier will now run on the generated service files to act as a test for that feature.
fixes: #70 
fixes: #75
> fix(hooks): generate other https methods

- .github/workflows/comment-release.yml
This PR, adds a workflow that can be triggered by a comment called `npm publish`, it will trigger a publication of the npm package under the pre tag.
> ci: add prelease comment trigger

- .github/workflows/comment-release.yml
This changes the npm versioning to use the git sha of the current PR and not the main branch.
There is some bug in the comment-release workflow when updating the github comment.
Getting errors saying `packageName is not a function`
I am trying to understand why that is happening.
https://github.com/7nohe/openapi-react-query-codegen/actions/runs/8888225124/job/24404700180
> ci: update comment-release workflow

- README.md
- src/cli.mts
We set this so that the default request file returns the request's body instead of the whole response object.
This changed in the underlying library at some point, so we must update our default value to match.
fixes: #95 
As this library relies on the response being the body, maybe we should think of disabling allowing consumers to change that option. Something to think about.
> fix(cli): set serviceResponse default value to body

- README.md
- examples/react-app/src/App.tsx
- src/common.mts
- src/createExports.mts
- src/createUseQuery.mts
- tests/__snapshots__/createSource.test.ts.snap
- tests/__snapshots__/generate.test.ts.snap
- tests/createExports.test.ts
This PR is to make it easier for consumers to invalidate queries.
This is achieved by exporting a new function that builds the query keys.
This function is used internally to build the queryKey for the hooks.
The new functions are the name of the `queryHook + key + 'Fn'` and the first letter is capitalized.
We capitalize the first letter because the lowercase 'use' is reserved for hooks and all our `queryHook` start with use.
```tsx
// example
import {
usePetServiceFindPetsByStatus,
usePetServiceAddPet,
UsePetServiceFindPetsByStatusKeyFn,
} from "../openapi/queries";
import React from 'react';
// App.tsx
function App() {
const [status, setStatus] = React.useState('available');
const { data } = usePetServiceFindPetsByStatus({ status });
const { mutate } = usePetServiceAddPet({
onSuccess: …
```
> feat: add query key function

- src/createImports.mts
- tests/__snapshots__/createSource.test.ts.snap
- tests/__snapshots__/generate.test.ts.snap
In some instances, the QueryClient import was not auto-detected by ts-morph.
The fix is to - Explicitly add the type import.
ts-morph doesn't seem to have an issue removing the import if it is not being used in a file.
> fix(prefetch): import QueryClient type

- README.md
- package.json
- src/createImports.mts
In this PR,
- Add scripts to the package.json that I use commonly
- Add a development section to README
- fix linting error from last merge
> chore(docs): add scripts and update readme, fix linting error

- src/createUseQuery.mts
- tests/__snapshots__/createSource.test.ts.snap
- tests/__snapshots__/generate.test.ts.snap
The query key functions for queries that don't take in additional request parameters don't allow for using additional query key input, but query hooks always take in a query key parameter. This leads to the query key parameter in hooks without additional input being unused variable, leading to TypeScript erroring. Fix this by always taking query key parameter in query key functions, and always using it in query hooks.
Fixes #112.
> fix: Use optional query keys also without parameters

- package.json
It seems `pnpm-lock.yaml` generated via pnpm version grater that `9` since there is `lockfileVersion: '9.0'` in its first line. 
It doesn't work with pnpm version lower than 9 so I added `packageManager` key to `package.json`. If you run `corepack enable` it will automatically use package manager from  `packageManager` key.
> [Chore] specify packageManager and its version in package.json

- src/common.mts
- tests/common.test.ts
Hello!  First, let me thank you for writing this library!  Please enjoy a cup of coffee on me!
We use your library for a project at my company and it's made our lives a lot easier!  We've been using `v0.5.3` for a while, but as part of another effort, I'm updating to `v1.4.1`.  I noticed that some of our OAPI documents are tripping up the react query codegen and wanted to investigate.
I forked your repo and built it locally (which btw required some liberal use of `any` casting to get the project to build on my M3 mac--node 20, TS 5.5.x--but I removed all of those before committing my fix).  I threw in some `console.logs` in `createUseMutation`, and in the `methodParameters` section, `refParam.type.getText(param)` was returning something  in the following shape (paths, param names and type …
> fix: Ensure that `getShortType` regex wildcard is non-greedy

- README.md
- src/cli.mts
- src/common.mts
- src/createExports.mts
- src/createSource.mts
- src/createUseQuery.mts
- src/generate.mts
- tests/__snapshots__/generate.test.ts.snap
- tests/createExports.test.ts
- tests/generate.test.ts
This adds a new argument `--initialPageParam` to customize the `initialPageParam` option passed to useInfiniteQuery. Defaults to 1.
Fixes #141.
---
When nextPageParam is set to meta.nextPage, split on . and generate the appropriately nested typehint:
```ts
getNextPageParam: response => (response as {
meta: {
nextPage: number;
};
}).meta.nextPage
```
Fixes https://github.com/7nohe/openapi-react-query-codegen/issues/142.
> Adding initialPageParam and nested nextPageParam support

- examples/nextjs-app/app/components/PaginatedPets.tsx
- examples/nextjs-app/package.json
- examples/petstore.yaml
- examples/react-app/package.json
- lefthook.yml
- src/cli.mts
- src/createUseQuery.mts
- tests/__snapshots__/createSource.test.ts.snap
- tests/__snapshots__/generate.test.ts.snap
- tests/createExports.test.ts
- tests/inputs/petstore.yaml
- tests/service.test.ts
> feat: Support string type for `pageParam` and `nextPageParam` options
